export const icons = [
  { name: "stepbackward", family: "AntDesign", translate: "voltar um passo" },
  { name: "forward", family: "AntDesign", translate: "avançar" },
  { name: "banckward", family: "AntDesign", translate: "voltar" },
  { name: "caretright", family: "AntDesign", translate: "seta para direita" },
  { name: "caretleft", family: "AntDesign", translate: "seta para esquerda" },
  { name: "caretdown", family: "AntDesign", translate: "seta para baixo" },
  { name: "caretup", family: "AntDesign", translate: "seta para cima" },
  { name: "rightcircle", family: "AntDesign", translate: "círculo à direita" },
  { name: "leftcircle", family: "AntDesign", translate: "círculo à esquerda" },
  { name: "like2", family: "AntDesign", translate: "curtir" },
  { name: "dislike2", family: "AntDesign", translate: "não curtir" },
  { name: "like1", family: "AntDesign", translate: "curtir" },
  { name: "dislike1", family: "AntDesign", translate: "não curtir" },
  { name: "bulb1", family: "AntDesign", translate: "lâmpada" },
  { name: "rocket1", family: "AntDesign", translate: "foguete" },
  { name: "select1", family: "AntDesign", translate: "selecionar" },
  { name: "apple1", family: "AntDesign", translate: "maçã" },
  { name: "apple-o", family: "AntDesign", translate: "maçã" },
  { name: "android1", family: "AntDesign", translate: "android" },
  { name: "android", family: "AntDesign", translate: "android" },
  {
    name: "aliwangwang-o1",
    family: "AntDesign",
    translate: "ícone de comunicação",
  },
  { name: "aliwangwang", family: "AntDesign", translate: "comunicação" },
  {
    name: "pay-circle1",
    family: "AntDesign",
    translate: "círculo de pagamento",
  },
  {
    name: "pay-circle-o1",
    family: "AntDesign",
    translate: "círculo de pagamento",
  },
  { name: "poweroff", family: "AntDesign", translate: "desligar" },
  { name: "trademark", family: "AntDesign", translate: "marca registrada" },
  { name: "find", family: "AntDesign", translate: "encontrar" },
  { name: "copyright", family: "AntDesign", translate: "direitos autorais" },
  { name: "sound", family: "AntDesign", translate: "som" },
  { name: "earth", family: "AntDesign", translate: "terra" },
  { name: "wifi", family: "AntDesign", translate: "wi-fi" },
  { name: "sync", family: "AntDesign", translate: "sincronizar" },
  { name: "login", family: "AntDesign", translate: "entrar" },
  { name: "logout", family: "AntDesign", translate: "sair" },
  { name: "reload1", family: "AntDesign", translate: "recarregar" },
  { name: "message1", family: "AntDesign", translate: "mensagem" },
  { name: "shake", family: "AntDesign", translate: "agitar" },
  { name: "API", family: "AntDesign", translate: "API" },
  { name: "appstore-o", family: "AntDesign", translate: "loja de aplicativos" },
  { name: "appstore1", family: "AntDesign", translate: "loja de aplicativos" },
  { name: "scan1", family: "AntDesign", translate: "escanear" },
  { name: "exception1", family: "AntDesign", translate: "exceção" },
  { name: "contacts", family: "AntDesign", translate: "contatos" },
  { name: "solution1", family: "AntDesign", translate: "solução" },
  { name: "fork", family: "AntDesign", translate: "bifurcação" },
  { name: "edit", family: "AntDesign", translate: "editar" },
  { name: "form", family: "AntDesign", translate: "formulário" },
  { name: "warning", family: "AntDesign", translate: "aviso" },
  { name: "table", family: "AntDesign", translate: "tabela" },
  { name: "profile", family: "AntDesign", translate: "perfil" },
  { name: "dashboard", family: "AntDesign", translate: "painel" },
  { name: "indent-left", family: "AntDesign", translate: "recuo esquerdo" },
  { name: "indent-right", family: "AntDesign", translate: "recuo direito" },
  { name: "menu-unfold", family: "AntDesign", translate: "menu expandir" },
  { name: "menu-fold", family: "AntDesign", translate: "menu recolher" },
  { name: "alipay-square", family: "AntDesign", translate: "quadrado alipay" },
  { name: "codepen-circle", family: "AntDesign", translate: "círculo codepen" },
  { name: "google", family: "AntDesign", translate: "google" },
  { name: "amazon", family: "AntDesign", translate: "amazon" },
  { name: "codepen", family: "AntDesign", translate: "codepen" },
  {
    name: "facebook-square",
    family: "AntDesign",
    translate: "quadrado facebook",
  },
  { name: "dropbox", family: "AntDesign", translate: "dropbox" },
  { name: "googleplus", family: "AntDesign", translate: "google plus" },
  {
    name: "linkedin-square",
    family: "AntDesign",
    translate: "quadrado linkedin",
  },
  {
    name: "medium-monogram",
    family: "AntDesign",
    translate: "logotipo medium",
  },
  { name: "gitlab", family: "AntDesign", translate: "gitlab" },
  { name: "medium-wordmark", family: "AntDesign", translate: "marca medium" },
  { name: "QQ", family: "AntDesign", translate: "QQ" },
  { name: "skype", family: "AntDesign", translate: "skype" },
  { name: "taobao-square", family: "AntDesign", translate: "quadrado taobao" },
  { name: "alipay-circle", family: "AntDesign", translate: "círculo alipay" },
  { name: "youtube", family: "AntDesign", translate: "youtube" },
  { name: "wechat", family: "AntDesign", translate: "wechat" },
  { name: "twitter", family: "AntDesign", translate: "twitter" },
  { name: "weibo", family: "AntDesign", translate: "weibo" },
  { name: "HTML", family: "AntDesign", translate: "HTML" },
  { name: "taobao-circle", family: "AntDesign", translate: "círculo taobao" },
  { name: "weibo-circle", family: "AntDesign", translate: "círculo weibo" },
  { name: "weibo-square", family: "AntDesign", translate: "quadrado weibo" },
  { name: "CodeSandbox", family: "AntDesign", translate: "caixa de código" },
  { name: "aliyun", family: "AntDesign", translate: "aliyun" },
  { name: "zhihu", family: "AntDesign", translate: "zhihu" },
  { name: "behance", family: "AntDesign", translate: "behance" },
  { name: "dribbble", family: "AntDesign", translate: "dribbble" },
  {
    name: "dribbble-square",
    family: "AntDesign",
    translate: "quadrado dribbble",
  },
  {
    name: "behance-square",
    family: "AntDesign",
    translate: "quadrado behance",
  },
  { name: "file-markdown", family: "AntDesign", translate: "arquivo markdown" },
  { name: "instagram", family: "AntDesign", translate: "instagram" },
  { name: "yuque", family: "AntDesign", translate: "yuque" },
  { name: "slack", family: "AntDesign", translate: "slack" },
  { name: "slack-square", family: "AntDesign", translate: "quadrado slack" },
  { name: "500px", family: "Entypo", translate: "500px" },
  { name: "500px-with-circle", family: "Entypo", translate: "círculo 500px" },
  { name: "add-to-list", family: "Entypo", translate: "adicionar à lista" },
  { name: "add-user", family: "Entypo", translate: "adicionar usuário" },
  { name: "address", family: "Entypo", translate: "endereço" },
  { name: "adjust", family: "Entypo", translate: "ajustar" },
  { name: "air", family: "Entypo", translate: "ar" },
  { name: "aircraft", family: "Entypo", translate: "aeronave" },
  {
    name: "aircraft-landing",
    family: "Entypo",
    translate: "pouso de aeronave",
  },
  {
    name: "aircraft-take-off",
    family: "Entypo",
    translate: "decolagem de aeronave",
  },
  { name: "skype", family: "Entypo", translate: "skype" },
  { name: "skype-with-circle", family: "Entypo", translate: "círculo skype" },
  { name: "slideshare", family: "Entypo", translate: "slideshare" },
  { name: "smashing", family: "Entypo", translate: "smashing" },
  { name: "sound", family: "Entypo", translate: "som" },
  { name: "sound-mix", family: "Entypo", translate: "mixagem de som" },
  { name: "sound-mute", family: "Entypo", translate: "som mudo" },
  { name: "soundcloud", family: "Entypo", translate: "soundcloud" },
  { name: "sports-club", family: "Entypo", translate: "clube esportivo" },
  { name: "spotify", family: "Entypo", translate: "spotify" },
  {
    name: "spotify-with-circle",
    family: "Entypo",
    translate: "círculo spotify",
  },
  { name: "spreadsheet", family: "Entypo", translate: "planilha" },
  { name: "squared-cross", family: "Entypo", translate: "cruz quadrada" },
  { name: "squared-minus", family: "Entypo", translate: "menos quadrado" },
  { name: "squared-plus", family: "Entypo", translate: "mais quadrado" },
  { name: "star", family: "Entypo", translate: "estrela" },
  { name: "star-outlined", family: "Entypo", translate: "estrela contornada" },
  { name: "stopwatch", family: "Entypo", translate: "cronômetro" },
  { name: "stumbleupon", family: "Entypo", translate: "stumbleupon" },
  {
    name: "stumbleupon-with-circle",
    family: "Entypo",
    translate: "círculo stumbleupon",
  },
  { name: "suitcase", family: "Entypo", translate: "mala" },
  { name: "swap", family: "Entypo", translate: "trocar" },
  { name: "swarm", family: "Entypo", translate: "swarm" },
  { name: "sweden", family: "Entypo", translate: "suécia" },
  { name: "switch", family: "Entypo", translate: "switch" },
  { name: "tablet", family: "Entypo", translate: "tablet" },
  {
    name: "tablet-mobile-combo",
    family: "Entypo",
    translate: "tablet-celular",
  },
  { name: "tag", family: "Entypo", translate: "etiqueta" },
  { name: "text", family: "Entypo", translate: "texto" },
  { name: "text-document", family: "Entypo", translate: "documento de texto" },
  {
    name: "text-document-inverted",
    family: "Entypo",
    translate: "documento de texto invertido",
  },
  { name: "thermometer", family: "Entypo", translate: "termômetro" },
  { name: "thumbs-down", family: "Entypo", translate: "descurtir" },
  { name: "thumbs-up", family: "Entypo", translate: "curtir" },
  { name: "thunder-cloud", family: "Entypo", translate: "nuvem de trovão" },
  { name: "ticket", family: "Entypo", translate: "ingresso" },
  { name: "time-slot", family: "Entypo", translate: "intervalo de tempo" },
  { name: "tools", family: "Entypo", translate: "ferramentas" },
  { name: "traffic-cone", family: "Entypo", translate: "cone de trânsito" },
  { name: "trash", family: "Entypo", translate: "lixeira" },
  { name: "tree", family: "Entypo", translate: "árvore" },
  {
    name: "triangle-down",
    family: "Entypo",
    translate: "triângulo para baixo",
  },
  {
    name: "triangle-left",
    family: "Entypo",
    translate: "triângulo para a esquerda",
  },
  {
    name: "triangle-right",
    family: "Entypo",
    translate: "triângulo para a direita",
  },
  { name: "triangle-up", family: "Entypo", translate: "triângulo para cima" },
  { name: "tripadvisor", family: "Entypo", translate: "tripadvisor" },
  { name: "trophy", family: "Entypo", translate: "troféu" },
  { name: "tumblr", family: "Entypo", translate: "tumblr" },
  {
    name: "tumblr-with-circle",
    family: "Entypo",
    translate: "tumblr com círculo",
  },
  { name: "tv", family: "Entypo", translate: "tv" },
  { name: "twitter", family: "Entypo", translate: "twitter" },
  {
    name: "twitter-with-circle",
    family: "Entypo",
    translate: "twitter com círculo",
  },
  { name: "typing", family: "Entypo", translate: "digitando" },
  { name: "uninstall", family: "Entypo", translate: "desinstalar" },
  { name: "unread", family: "Entypo", translate: "não lido" },
  { name: "untag", family: "Entypo", translate: "remover etiqueta" },
  { name: "upload", family: "Entypo", translate: "enviar" },
  {
    name: "upload-to-cloud",
    family: "Entypo",
    translate: "enviar para a nuvem",
  },
  { name: "user", family: "Entypo", translate: "usuário" },
  { name: "users", family: "Entypo", translate: "usuários" },
  { name: "v-card", family: "Entypo", translate: "cartão virtual" },
  { name: "video", family: "Entypo", translate: "vídeo" },
  { name: "video-camera", family: "Entypo", translate: "filmadora" },
  { name: "vimeo", family: "Entypo", translate: "vimeo" },
  {
    name: "vimeo-with-circle",
    family: "Entypo",
    translate: "vimeo com círculo",
  },
  { name: "vine", family: "Entypo", translate: "vine" },
  { name: "vine-with-circle", family: "Entypo", translate: "vine com círculo" },
  { name: "vinyl", family: "Entypo", translate: "vinil" },
  { name: "vk", family: "Entypo", translate: "vk" },
  { name: "vk-alternitive", family: "Entypo", translate: "vk alternativo" },
  { name: "vk-with-circle", family: "Entypo", translate: "vk com círculo" },
  { name: "voicemail", family: "Entypo", translate: "correio de voz" },
  { name: "wallet", family: "Entypo", translate: "carteira" },
  { name: "warning", family: "Entypo", translate: "aviso" },
  { name: "water", family: "Entypo", translate: "água" },
  { name: "windows-store", family: "Entypo", translate: "loja do windows" },
  { name: "xing", family: "Entypo", translate: "xing" },
  { name: "xing-with-circle", family: "Entypo", translate: "xing com círculo" },
  { name: "yelp", family: "Entypo", translate: "yelp" },
  { name: "youko", family: "Entypo", translate: "youko" },
  {
    name: "youko-with-circle",
    family: "Entypo",
    translate: "youko com círculo",
  },
  { name: "youtube", family: "Entypo", translate: "youtube" },
  {
    name: "youtube-with-circle",
    family: "Entypo",
    translate: "youtube com círculo",
  },
  { name: "archive", family: "EvilIcons", translate: "arquivo" },
  { name: "arrow-down", family: "EvilIcons", translate: "seta para baixo" },
  {
    name: "arrow-left",
    family: "EvilIcons",
    translate: "seta para a esquerda",
  },
  {
    name: "arrow-right",
    family: "EvilIcons",
    translate: "seta para a direita",
  },
  { name: "arrow-up", family: "EvilIcons", translate: "seta para cima" },
  { name: "bell", family: "EvilIcons", translate: "sino" },
  { name: "calendar", family: "EvilIcons", translate: "calendário" },
  { name: "camera", family: "EvilIcons", translate: "câmera" },
  { name: "cart", family: "EvilIcons", translate: "carrinho" },
  { name: "chart", family: "EvilIcons", translate: "gráfico" },
  { name: "check", family: "EvilIcons", translate: "verificar" },
  { name: "chevron-down", family: "EvilIcons", translate: "seta para baixo" },
  {
    name: "chevron-left",
    family: "EvilIcons",
    translate: "seta para a esquerda",
  },
  {
    name: "chevron-right",
    family: "EvilIcons",
    translate: "seta para a direita",
  },
  { name: "chevron-up", family: "EvilIcons", translate: "seta para cima" },
  { name: "clock", family: "EvilIcons", translate: "relógio" },
  { name: "close", family: "EvilIcons", translate: "fechar" },
  { name: "close-o", family: "EvilIcons", translate: "fechar" },
  { name: "comment", family: "EvilIcons", translate: "comentário" },
  { name: "credit-card", family: "EvilIcons", translate: "cartão de crédito" },
  { name: "envelope", family: "EvilIcons", translate: "envelope" },
  { name: "exclamation", family: "EvilIcons", translate: "exclamação" },
  { name: "external-link", family: "EvilIcons", translate: "link externo" },
  { name: "eye", family: "EvilIcons", translate: "olho" },
  { name: "gear", family: "EvilIcons", translate: "engrenagem" },
  { name: "heart", family: "EvilIcons", translate: "coração" },
  { name: "image", family: "EvilIcons", translate: "imagem" },
  { name: "like", family: "EvilIcons", translate: "curtir" },
  { name: "link", family: "EvilIcons", translate: "link" },
  { name: "location", family: "EvilIcons", translate: "localização" },
  { name: "lock", family: "EvilIcons", translate: "cadeado" },
  { name: "minus", family: "EvilIcons", translate: "menos" },
  { name: "navicon", family: "EvilIcons", translate: "menu" },
  { name: "paperclip", family: "EvilIcons", translate: "clipe de papel" },
  { name: "pencil", family: "EvilIcons", translate: "lápis" },
  { name: "play", family: "EvilIcons", translate: "reproduzir" },
  { name: "plus", family: "EvilIcons", translate: "mais" },
  { name: "pointer", family: "EvilIcons", translate: "ponteiro" },
  { name: "question", family: "EvilIcons", translate: "interrogação" },
  { name: "redo", family: "EvilIcons", translate: "refazer" },
  { name: "refresh", family: "EvilIcons", translate: "atualizar" },
  { name: "retweet", family: "EvilIcons", translate: "retweet" },
  { name: "sc-facebook", family: "EvilIcons", translate: "facebook" },
  { name: "sc-github", family: "EvilIcons", translate: "github" },
  { name: "sc-google-plus", family: "EvilIcons", translate: "google plus" },
  { name: "sc-instagram", family: "EvilIcons", translate: "instagram" },
  { name: "sc-linkedin", family: "EvilIcons", translate: "linkedin" },
  { name: "sc-odnoklassniki", family: "EvilIcons", translate: "odnoklassniki" },
  { name: "sc-pinterest", family: "EvilIcons", translate: "pinterest" },
  { name: "sc-skype", family: "EvilIcons", translate: "skype" },
  { name: "sc-soundcloud", family: "EvilIcons", translate: "soundcloud" },
  { name: "sc-telegram", family: "EvilIcons", translate: "telegram" },
  { name: "sc-tumblr", family: "EvilIcons", translate: "tumblr" },
  { name: "sc-twitter", family: "EvilIcons", translate: "twitter" },
  { name: "sc-vimeo", family: "EvilIcons", translate: "vimeo" },
  { name: "sc-vk", family: "EvilIcons", translate: "vk" },
  { name: "sc-youtube", family: "EvilIcons", translate: "youtube" },
  { name: "search", family: "EvilIcons", translate: "pesquisar" },
  {
    name: "share-apple",
    family: "EvilIcons",
    translate: "compartilhar (Apple)",
  },
  {
    name: "share-google",
    family: "EvilIcons",
    translate: "compartilhar (Google)",
  },
  { name: "spinner", family: "EvilIcons", translate: "carregando" },
  { name: "spinner-2", family: "EvilIcons", translate: "carregando 2" },
  { name: "spinner-3", family: "EvilIcons", translate: "carregando 3" },
  { name: "star", family: "EvilIcons", translate: "estrela" },
  { name: "tag", family: "EvilIcons", translate: "etiqueta" },
  { name: "trash", family: "EvilIcons", translate: "lixeira" },
  { name: "trophy", family: "EvilIcons", translate: "troféu" },
  { name: "undo", family: "EvilIcons", translate: "desfazer" },
  { name: "unlock", family: "EvilIcons", translate: "desbloquear" },
  { name: "user", family: "EvilIcons", translate: "usuário" },
  { name: "activity", family: "Feather", translate: "atividade" },
  { name: "airplay", family: "Feather", translate: "transmissão" },
  { name: "alert-circle", family: "Feather", translate: "alerta-círculo" },
  { name: "alert-octagon", family: "Feather", translate: "alerta-octógono" },
  { name: "alert-triangle", family: "Feather", translate: "alerta-triângulo" },
  { name: "align-center", family: "Feather", translate: "alinhar-centro" },
  {
    name: "align-justify",
    family: "Feather",
    translate: "alinhar-justificado",
  },
  { name: "align-left", family: "Feather", translate: "alinhar-esquerda" },
  { name: "align-right", family: "Feather", translate: "alinhar-direita" },
  { name: "anchor", family: "Feather", translate: "âncora" },
  {
    name: "shopping-cart",
    family: "Feather",
    translate: "carrinho-de-compras",
  },
  { name: "shuffle", family: "Feather", translate: "embaralhar" },
  { name: "sidebar", family: "Feather", translate: "barra-lateral" },
  { name: "skip-back", family: "Feather", translate: "voltar" },
  { name: "skip-forward", family: "Feather", translate: "avançar" },
  { name: "slack", family: "Feather", translate: "slack" },
  { name: "slash", family: "Feather", translate: "barra" },
  { name: "sliders", family: "Feather", translate: "deslizadores" },
  { name: "smartphone", family: "Feather", translate: "smartphone" },
  { name: "smile", family: "Feather", translate: "sorriso" },
  { name: "speaker", family: "Feather", translate: "alto-falante" },
  { name: "square", family: "Feather", translate: "quadrado" },
  { name: "star", family: "Feather", translate: "estrela" },
  { name: "stop-circle", family: "Feather", translate: "parar-círculo" },
  { name: "sun", family: "Feather", translate: "sol" },
  { name: "sunrise", family: "Feather", translate: "nascer-do-sol" },
  { name: "sunset", family: "Feather", translate: "pôr-do-sol" },
  { name: "tablet", family: "Feather", translate: "tablet" },
  { name: "tag", family: "Feather", translate: "etiqueta" },
  { name: "target", family: "Feather", translate: "alvo" },
  { name: "terminal", family: "Feather", translate: "terminal" },
  { name: "thermometer", family: "Feather", translate: "termômetro" },
  { name: "thumbs-down", family: "Feather", translate: "negativo" },
  { name: "thumbs-up", family: "Feather", translate: "positivo" },
  { name: "toggle-left", family: "Feather", translate: "alternar-esquerda" },
  { name: "toggle-right", family: "Feather", translate: "alternar-direita" },
  { name: "tool", family: "Feather", translate: "ferramenta" },
  { name: "trash", family: "Feather", translate: "lixeira" },
  { name: "trash-2", family: "Feather", translate: "lixeira-2" },
  { name: "trello", family: "Feather", translate: "trello" },
  { name: "trending-down", family: "Feather", translate: "tendência-baixa" },
  { name: "trending-up", family: "Feather", translate: "tendência-alta" },
  { name: "triangle", family: "Feather", translate: "triângulo" },
  { name: "truck", family: "Feather", translate: "caminhão" },
  { name: "tv", family: "Feather", translate: "televisão" },
  { name: "twitch", family: "Feather", translate: "twitch" },
  { name: "twitter", family: "Feather", translate: "twitter" },
  { name: "type", family: "Feather", translate: "tipo" },
  { name: "umbrella", family: "Feather", translate: "guarda-chuva" },
  { name: "underline", family: "Feather", translate: "sublinhado" },
  { name: "unlock", family: "Feather", translate: "desbloquear" },
  { name: "upload", family: "Feather", translate: "fazer-upload" },
  { name: "upload-cloud", family: "Feather", translate: "upload-nuvem" },
  { name: "user", family: "Feather", translate: "usuário" },
  { name: "user-check", family: "Feather", translate: "usuário-verificado" },
  { name: "user-minus", family: "Feather", translate: "remover-usuário" },
  { name: "user-plus", family: "Feather", translate: "adicionar-usuário" },
  { name: "user-x", family: "Feather", translate: "bloquear-usuário" },
  { name: "users", family: "Feather", translate: "usuários" },
  { name: "video", family: "Feather", translate: "vídeo" },
  { name: "video-off", family: "Feather", translate: "vídeo-desativado" },
  { name: "voicemail", family: "Feather", translate: "correio-de-voz" },
  { name: "volume", family: "Feather", translate: "volume" },
  { name: "volume-1", family: "Feather", translate: "volume-baixo" },
  { name: "volume-2", family: "Feather", translate: "volume-médio" },
  { name: "volume-x", family: "Feather", translate: "volume-mudo" },
  { name: "watch", family: "Feather", translate: "relógio" },
  { name: "wifi", family: "Feather", translate: "wifi" },
  { name: "wifi-off", family: "Feather", translate: "wifi-desativado" },
  { name: "wind", family: "Feather", translate: "vento" },
  { name: "x", family: "Feather", translate: "fechar" },
  { name: "x-circle", family: "Feather", translate: "fechar-círculo" },
  { name: "x-octagon", family: "Feather", translate: "fechar-octógono" },
  { name: "x-square", family: "Feather", translate: "fechar-quadrado" },
  { name: "youtube", family: "Feather", translate: "youtube" },
  { name: "zap", family: "Feather", translate: "relâmpago" },
  { name: "zap-off", family: "Feather", translate: "relâmpago-desativado" },
  { name: "zoom-in", family: "Feather", translate: "aproximar" },
  { name: "zoom-out", family: "Feather", translate: "afastar" },
  { name: "low-vision", family: "FontAwesome", translate: "baixa-visão" },
  { name: "viadeo", family: "FontAwesome", translate: "viadeo" },
  {
    name: "viadeo-square",
    family: "FontAwesome",
    translate: "viadeo-quadrado",
  },
  { name: "snapchat", family: "FontAwesome", translate: "snapchat" },
  {
    name: "snapchat-ghost",
    family: "FontAwesome",
    translate: "snapchat-fantasma",
  },
  {
    name: "snapchat-square",
    family: "FontAwesome",
    translate: "snapchat-quadrado",
  },
  { name: "pied-piper", family: "FontAwesome", translate: "pied-piper" },
  { name: "first-order", family: "FontAwesome", translate: "primeira-ordem" },
  { name: "yoast", family: "FontAwesome", translate: "yoast" },
  { name: "themeisle", family: "FontAwesome", translate: "themeisle" },
  {
    name: "google-plus-circle",
    family: "FontAwesome",
    translate: "google-plus-círculo",
  },
  {
    name: "google-plus-official",
    family: "FontAwesome",
    translate: "google-plus-oficial",
  },
  { name: "fa", family: "FontAwesome", translate: "font-awesome" },
  { name: "font-awesome", family: "FontAwesome", translate: "font-awesome" },
  { name: "handshake-o", family: "FontAwesome", translate: "aperto-de-mão" },
  {
    name: "envelope-open",
    family: "FontAwesome",
    translate: "envelope-aberto",
  },
  {
    name: "envelope-open-o",
    family: "FontAwesome",
    translate: "envelope-aberto-o",
  },
  { name: "linode", family: "FontAwesome", translate: "linode" },
  {
    name: "address-book",
    family: "FontAwesome",
    translate: "livro-de-endereços",
  },
  {
    name: "address-book-o",
    family: "FontAwesome",
    translate: "livro-de-endereços-o",
  },
  { name: "vcard", family: "FontAwesome", translate: "vcard" },
  {
    name: "address-card",
    family: "FontAwesome",
    translate: "cartão-de-endereço",
  },
  { name: "vcard-o", family: "FontAwesome", translate: "vcard-o" },
  {
    name: "address-card-o",
    family: "FontAwesome",
    translate: "cartão-de-endereço-o",
  },
  {
    name: "user-circle",
    family: "FontAwesome",
    translate: "círculo-de-usuário",
  },
  {
    name: "user-circle-o",
    family: "FontAwesome",
    translate: "círculo-de-usuário-o",
  },
  { name: "user-o", family: "FontAwesome", translate: "usuário-o" },
  { name: "id-badge", family: "FontAwesome", translate: "crachá" },
  {
    name: "drivers-license",
    family: "FontAwesome",
    translate: "carteira-de-motorista",
  },
  { name: "id-card", family: "FontAwesome", translate: "identidade" },
  {
    name: "drivers-license-o",
    family: "FontAwesome",
    translate: "carteira-de-motorista-o",
  },
  { name: "id-card-o", family: "FontAwesome", translate: "identidade-o" },
  { name: "quora", family: "FontAwesome", translate: "quora" },
  {
    name: "free-code-camp",
    family: "FontAwesome",
    translate: "free-code-camp",
  },
  { name: "telegram", family: "FontAwesome", translate: "telegram" },
  { name: "thermometer-4", family: "FontAwesome", translate: "termômetro-4" },
  { name: "thermometer", family: "FontAwesome", translate: "termômetro" },
  {
    name: "thermometer-full",
    family: "FontAwesome",
    translate: "termômetro-cheio",
  },
  { name: "thermometer-3", family: "FontAwesome", translate: "termômetro-3" },
  {
    name: "thermometer-three-quarters",
    family: "FontAwesome",
    translate: "termômetro-três-quartos",
  },
  { name: "thermometer-2", family: "FontAwesome", translate: "termômetro-2" },
  {
    name: "thermometer-half",
    family: "FontAwesome",
    translate: "termômetro-metade",
  },
  { name: "thermometer-1", family: "FontAwesome", translate: "termômetro-1" },
  {
    name: "thermometer-quarter",
    family: "FontAwesome",
    translate: "termômetro-quarto",
  },
  { name: "thermometer-0", family: "FontAwesome", translate: "termômetro-0" },
  {
    name: "thermometer-empty",
    family: "FontAwesome",
    translate: "termômetro-vazio",
  },
  { name: "shower", family: "FontAwesome", translate: "chuveiro" },
  { name: "bathtub", family: "FontAwesome", translate: "banheira" },
  { name: "s15", family: "FontAwesome", translate: "s15" },
  { name: "bath", family: "FontAwesome", translate: "banho" },
  { name: "podcast", family: "FontAwesome", translate: "podcast" },
  {
    name: "window-maximize",
    family: "FontAwesome",
    translate: "janela-maximizar",
  },
  {
    name: "window-minimize",
    family: "FontAwesome",
    translate: "janela-minimizar",
  },
  {
    name: "window-restore",
    family: "FontAwesome",
    translate: "janela-restaurar",
  },
  {
    name: "times-rectangle",
    family: "FontAwesome",
    translate: "retângulo-fechar",
  },
  { name: "window-close", family: "FontAwesome", translate: "janela-fechar" },
  {
    name: "times-rectangle-o",
    family: "FontAwesome",
    translate: "retângulo-fechar-o",
  },
  {
    name: "window-close-o",
    family: "FontAwesome",
    translate: "janela-fechar-o",
  },
  { name: "bandcamp", family: "FontAwesome", translate: "bandcamp" },
  { name: "grav", family: "FontAwesome", translate: "grav" },
  { name: "etsy", family: "FontAwesome", translate: "etsy" },
  { name: "imdb", family: "FontAwesome", translate: "imdb" },
  { name: "ravelry", family: "FontAwesome", translate: "ravelry" },
  { name: "eercast", family: "FontAwesome", translate: "eercast" },
  { name: "microchip", family: "FontAwesome", translate: "microchip" },
  { name: "snowflake-o", family: "FontAwesome", translate: "floco-de-neve" },
  { name: "superpowers", family: "FontAwesome", translate: "superpoderes" },
  { name: "wpexplorer", family: "FontAwesome", translate: "wpexplorer" },
  { name: "meetup", family: "FontAwesome", translate: "meetup" },
  { name: "500px", family: "FontAwesome5", translate: "500px" },
  {
    name: "accessible-icon",
    family: "FontAwesome5",
    translate: "ícone acessível",
  },
  { name: "accusoft", family: "FontAwesome5", translate: "accusoft" },
  {
    name: "acquisitions-incorporated",
    family: "FontAwesome5",
    translate: "aquisições incorporadas",
  },
  { name: "ad", family: "FontAwesome5", translate: "anúncio" },
  {
    name: "address-book",
    family: "FontAwesome5",
    translate: "livro de endereços",
  },
  {
    name: "address-card",
    family: "FontAwesome5",
    translate: "cartão de endereço",
  },
  { name: "adjust", family: "FontAwesome5", translate: "ajustar" },
  { name: "adn", family: "FontAwesome5", translate: "adn" },
  { name: "adversal", family: "FontAwesome5", translate: "adversal" },
  { name: "virus-slash", family: "FontAwesome5", translate: "vírus cortado" },
  { name: "viruses", family: "FontAwesome5", translate: "vírus" },
  { name: "vk", family: "FontAwesome5", translate: "vk" },
  { name: "vnv", family: "FontAwesome5", translate: "vnv" },
  { name: "voicemail", family: "FontAwesome5", translate: "correio de voz" },
  {
    name: "volleyball-ball",
    family: "FontAwesome5",
    translate: "bola de vôlei",
  },
  {
    name: "volume-down",
    family: "FontAwesome5",
    translate: "volume para baixo",
  },
  { name: "volume-mute", family: "FontAwesome5", translate: "volume mudo" },
  { name: "volume-off", family: "FontAwesome5", translate: "volume desligado" },
  { name: "volume-up", family: "FontAwesome5", translate: "volume para cima" },
  { name: "vote-yea", family: "FontAwesome5", translate: "voto sim" },
  {
    name: "vr-cardboard",
    family: "FontAwesome5",
    translate: "óculos de realidade virtual de papelão",
  },
  { name: "vuejs", family: "FontAwesome5", translate: "vuejs" },
  { name: "walking", family: "FontAwesome5", translate: "caminhando" },
  { name: "wallet", family: "FontAwesome5", translate: "carteira" },
  { name: "warehouse", family: "FontAwesome5", translate: "armazém" },
  {
    name: "watchman-monitoring",
    family: "FontAwesome5",
    translate: "monitoramento do vigia",
  },
  { name: "water", family: "FontAwesome5", translate: "água" },
  { name: "wave-square", family: "FontAwesome5", translate: "onda quadrada" },
  { name: "waze", family: "FontAwesome5", translate: "waze" },
  { name: "weebly", family: "FontAwesome5", translate: "weebly" },
  { name: "weibo", family: "FontAwesome5", translate: "weibo" },
  { name: "weight", family: "FontAwesome5", translate: "peso" },
  {
    name: "weight-hanging",
    family: "FontAwesome5",
    translate: "peso pendurado",
  },
  { name: "weixin", family: "FontAwesome5", translate: "weixin" },
  { name: "whatsapp", family: "FontAwesome5", translate: "whatsapp" },
  {
    name: "whatsapp-square",
    family: "FontAwesome5",
    translate: "whatsapp quadrado",
  },
  { name: "wheelchair", family: "FontAwesome5", translate: "cadeira de rodas" },
  { name: "whmcs", family: "FontAwesome5", translate: "whmcs" },
  { name: "wifi", family: "FontAwesome5", translate: "wifi" },
  { name: "wikipedia-w", family: "FontAwesome5", translate: "wikipedia w" },
  { name: "wind", family: "FontAwesome5", translate: "vento" },
  { name: "window-close", family: "FontAwesome5", translate: "fechar janela" },
  {
    name: "window-maximize",
    family: "FontAwesome5",
    translate: "maximizar janela",
  },
  {
    name: "window-minimize",
    family: "FontAwesome5",
    translate: "minimizar janela",
  },
  {
    name: "window-restore",
    family: "FontAwesome5",
    translate: "restaurar janela",
  },
  { name: "windows", family: "FontAwesome5", translate: "windows" },
  {
    name: "wine-bottle",
    family: "FontAwesome5",
    translate: "garrafa de vinho",
  },
  { name: "wine-glass", family: "FontAwesome5", translate: "taça de vinho" },
  {
    name: "wine-glass-alt",
    family: "FontAwesome5",
    translate: "taça de vinho alternativa",
  },
  { name: "wix", family: "FontAwesome5", translate: "wix" },
  {
    name: "wizards-of-the-coast",
    family: "FontAwesome5",
    translate: "feiticeiros da costa",
  },
  { name: "wodu", family: "FontAwesome5", translate: "wodu" },
  {
    name: "wolf-pack-battalion",
    family: "FontAwesome5",
    translate: "batalhão de lobos",
  },
  { name: "won-sign", family: "FontAwesome5", translate: "símbolo do won" },
  { name: "wordpress", family: "FontAwesome5", translate: "wordpress" },
  {
    name: "wordpress-simple",
    family: "FontAwesome5",
    translate: "wordpress simples",
  },
  { name: "wpbeginner", family: "FontAwesome5", translate: "wp beginner" },
  { name: "wpexplorer", family: "FontAwesome5", translate: "wp explorer" },
  { name: "wpforms", family: "FontAwesome5", translate: "wpforms" },
  { name: "wpressr", family: "FontAwesome5", translate: "wpressr" },
  { name: "wrench", family: "FontAwesome5", translate: "chave inglesa" },
  { name: "x-ray", family: "FontAwesome5", translate: "raio-x" },
  { name: "xbox", family: "FontAwesome5", translate: "xbox" },
  { name: "xing", family: "FontAwesome5", translate: "xing" },
  { name: "xing-square", family: "FontAwesome5", translate: "xing quadrado" },
  { name: "y-combinator", family: "FontAwesome5", translate: "y combinator" },
  { name: "yahoo", family: "FontAwesome5", translate: "yahoo" },
  { name: "yammer", family: "FontAwesome5", translate: "yammer" },
  { name: "yandex", family: "FontAwesome5", translate: "yandex" },
  {
    name: "yandex-international",
    family: "FontAwesome5",
    translate: "yandex internacional",
  },
  { name: "yarn", family: "FontAwesome5", translate: "fio" },
  { name: "yelp", family: "FontAwesome5", translate: "yelp" },
  { name: "yen-sign", family: "FontAwesome5", translate: "símbolo do iene" },
  { name: "yin-yang", family: "FontAwesome5", translate: "yin yang" },
  { name: "yoast", family: "FontAwesome5", translate: "yoast" },
  { name: "youtube", family: "FontAwesome5", translate: "youtube" },
  {
    name: "youtube-square",
    family: "FontAwesome5",
    translate: "youtube quadrado",
  },
  { name: "zhihu", family: "FontAwesome5", translate: "zhihu" },
  { name: "0", family: "FontAwesome6", translate: "zero" },
  { name: "1", family: "FontAwesome6", translate: "um" },
  { name: "2", family: "FontAwesome6", translate: "dois" },
  { name: "3", family: "FontAwesome6", translate: "três" },
  { name: "4", family: "FontAwesome6", translate: "quatro" },
  { name: "5", family: "FontAwesome6", translate: "cinco" },
  { name: "6", family: "FontAwesome6", translate: "seis" },
  { name: "7", family: "FontAwesome6", translate: "sete" },
  { name: "8", family: "FontAwesome6", translate: "oito" },
  { name: "9", family: "FontAwesome6", translate: "nove" },
  { name: "cc-amex", family: "FontAwesome6", translate: "cartão-amex" },
  { name: "uber", family: "FontAwesome6", translate: "uber" },
  { name: "github", family: "FontAwesome6", translate: "github" },
  { name: "php", family: "FontAwesome6", translate: "php" },
  { name: "alipay", family: "FontAwesome6", translate: "alipay" },
  { name: "youtube", family: "FontAwesome6", translate: "youtube" },
  { name: "skyatlas", family: "FontAwesome6", translate: "skyatlas" },
  {
    name: "firefox-browser",
    family: "FontAwesome6",
    translate: "navegador-firefox",
  },
  { name: "replyd", family: "FontAwesome6", translate: "replyd" },
  { name: "suse", family: "FontAwesome6", translate: "suse" },
  { name: "jenkins", family: "FontAwesome6", translate: "jenkins" },
  { name: "twitter", family: "FontAwesome6", translate: "twitter" },
  { name: "rockrms", family: "FontAwesome6", translate: "rockrms" },
  { name: "pinterest", family: "FontAwesome6", translate: "pinterest" },
  { name: "buffer", family: "FontAwesome6", translate: "buffer" },
  { name: "npm", family: "FontAwesome6", translate: "npm" },
  { name: "yammer", family: "FontAwesome6", translate: "yammer" },
  { name: "btc", family: "FontAwesome6", translate: "btc" },
  { name: "dribbble", family: "FontAwesome6", translate: "dribbble" },
  {
    name: "stumbleupon-circle",
    family: "FontAwesome6",
    translate: "círculo-stumbleupon",
  },
  {
    name: "internet-explorer",
    family: "FontAwesome6",
    translate: "internet-explorer",
  },
  { name: "stubber", family: "FontAwesome6", translate: "stubber" },
  { name: "telegram", family: "FontAwesome6", translate: "telegram" },
  {
    name: "telegram-plane",
    family: "FontAwesome6",
    translate: "avião-telegram",
  },
  {
    name: "old-republic",
    family: "FontAwesome6",
    translate: "velha-república",
  },
  { name: "odysee", family: "FontAwesome6", translate: "odysee" },
  {
    name: "square-whatsapp",
    family: "FontAwesome6",
    translate: "quadrado-whatsapp",
  },
  {
    name: "whatsapp-square",
    family: "FontAwesome6",
    translate: "quadrado-whatsapp",
  },
  { name: "node-js", family: "FontAwesome6", translate: "node-js" },
  { name: "edge-legacy", family: "FontAwesome6", translate: "edge-legado" },
  { name: "slack", family: "FontAwesome6", translate: "slack" },
  { name: "slack-hash", family: "FontAwesome6", translate: "hash-slack" },
  { name: "medrt", family: "FontAwesome6", translate: "medrt" },
  { name: "usb", family: "FontAwesome6", translate: "usb" },
  { name: "tumblr", family: "FontAwesome6", translate: "tumblr" },
  { name: "vaadin", family: "FontAwesome6", translate: "vaadin" },
  { name: "quora", family: "FontAwesome6", translate: "quora" },
  {
    name: "square-x-twitter",
    family: "FontAwesome6",
    translate: "quadrado-x-twitter",
  },
  { name: "reacteurope", family: "FontAwesome6", translate: "reacteurope" },
  { name: "medium", family: "FontAwesome6", translate: "medium" },
  { name: "medium-m", family: "FontAwesome6", translate: "medium-m" },
  { name: "amilia", family: "FontAwesome6", translate: "amilia" },
  { name: "mixcloud", family: "FontAwesome6", translate: "mixcloud" },
  { name: "flipboard", family: "FontAwesome6", translate: "flipboard" },
  { name: "viacoin", family: "FontAwesome6", translate: "viacoin" },
  { name: "critical-role", family: "FontAwesome6", translate: "papel-crítico" },
  { name: "sitrox", family: "FontAwesome6", translate: "sitrox" },
  { name: "discourse", family: "FontAwesome6", translate: "discurso" },
  { name: "joomla", family: "FontAwesome6", translate: "joomla" },
  { name: "mastodon", family: "FontAwesome6", translate: "mastodon" },
  { name: "airbnb", family: "FontAwesome6", translate: "airbnb" },
  {
    name: "wolf-pack-battalion",
    family: "FontAwesome6",
    translate: "batalhão-lobo",
  },
  { name: "buy-n-large", family: "FontAwesome6", translate: "buy-n-large" },
  { name: "gulp", family: "FontAwesome6", translate: "gulp" },
  {
    name: "creative-commons-sampling-plus",
    family: "FontAwesome6",
    translate: "creative-commons-sampling-plus",
  },
  { name: "strava", family: "FontAwesome6", translate: "strava" },
  { name: "ember", family: "FontAwesome6", translate: "ember" },
  {
    name: "canadian-maple-leaf",
    family: "FontAwesome6",
    translate: "folha-de bordo-canadense",
  },
  { name: "teamspeak", family: "FontAwesome6", translate: "teamspeak" },
  { name: "pushed", family: "FontAwesome6", translate: "pushed" },
  {
    name: "wordpress-simple",
    family: "FontAwesome6",
    translate: "wordpress-simples",
  },
  { name: "nutritionix", family: "FontAwesome6", translate: "nutritionix" },
  { name: "wodu", family: "FontAwesome6", translate: "wodu" },
  { name: "google-pay", family: "FontAwesome6", translate: "google-pay" },
  { name: "intercom", family: "FontAwesome6", translate: "intercom" },
  { name: "zhihu", family: "FontAwesome6", translate: "zhihu" },
  { name: "korvue", family: "FontAwesome6", translate: "korvue" },
  { name: "pix", family: "FontAwesome6", translate: "pix" },
  { name: "steam-symbol", family: "FontAwesome6", translate: "símbolo-steam" },
  { name: "acrobat-reader", family: "Fontisto", translate: "leitor-acrobat" },
  { name: "applemusic", family: "Fontisto", translate: "apple-music" },
  { name: "atlassian", family: "Fontisto", translate: "atlassian" },
  { name: "aws", family: "Fontisto", translate: "aws" },
  { name: "baidu", family: "Fontisto", translate: "baidu" },
  { name: "bing", family: "Fontisto", translate: "bing" },
  { name: "bower", family: "Fontisto", translate: "bower" },
  { name: "dailymotion", family: "Fontisto", translate: "dailymotion" },
  { name: "delicious", family: "Fontisto", translate: "delicioso" },
  { name: "deviantart", family: "Fontisto", translate: "deviantart" },
  { name: "venus", family: "Fontisto", translate: "venus" },
  { name: "automobile", family: "Fontisto", translate: "automóvel" },
  { name: "bicycle", family: "Fontisto", translate: "bicicleta" },
  { name: "bus", family: "Fontisto", translate: "ônibus" },
  { name: "car", family: "Fontisto", translate: "carro" },
  { name: "helicopter", family: "Fontisto", translate: "helicóptero" },
  { name: "metro", family: "Fontisto", translate: "metrô" },
  { name: "motorcycle", family: "Fontisto", translate: "motocicleta" },
  { name: "plane", family: "Fontisto", translate: "avião" },
  { name: "rocket", family: "Fontisto", translate: "foguete" },
  { name: "ship", family: "Fontisto", translate: "navio" },
  { name: "subway", family: "Fontisto", translate: "metrô" },
  { name: "taxi", family: "Fontisto", translate: "táxi" },
  { name: "train", family: "Fontisto", translate: "trem" },
  { name: "truck", family: "Fontisto", translate: "caminhão" },
  { name: "yacht", family: "Fontisto", translate: "iate" },
  { name: "beach-slipper", family: "Fontisto", translate: "chinelo-de-praia" },
  { name: "bus-ticket", family: "Fontisto", translate: "bilhete-de-ônibus" },
  { name: "cocktail", family: "Fontisto", translate: "coquetel" },
  { name: "compass-alt", family: "Fontisto", translate: "bússola-alt" },
  { name: "direction-sign", family: "Fontisto", translate: "placa-de-direção" },
  { name: "do-not-disturb", family: "Fontisto", translate: "não-disturbe" },
  {
    name: "flotation-ring",
    family: "Fontisto",
    translate: "anel-de-flutuação",
  },
  { name: "holiday-village", family: "Fontisto", translate: "vila-de-ferias" },
  {
    name: "hot-air-balloon",
    family: "Fontisto",
    translate: "balão-de-ar-quente",
  },
  { name: "hotel-alt", family: "Fontisto", translate: "hotel-alt" },
  { name: "hotel", family: "Fontisto", translate: "hotel" },
  { name: "island", family: "Fontisto", translate: "ilha" },
  {
    name: "money-symbol",
    family: "Fontisto",
    translate: "símbolo-de-dinheiro",
  },
  { name: "parasol", family: "Fontisto", translate: "guarda-sol" },
  { name: "passport-alt", family: "Fontisto", translate: "passaporte-alt" },
  { name: "passport", family: "Fontisto", translate: "passaporte" },
  { name: "photograph", family: "Fontisto", translate: "fotografia" },
  { name: "plane-ticket", family: "Fontisto", translate: "bilhete-de-avião" },
  { name: "room", family: "Fontisto", translate: "quarto" },
  { name: "sait-boat", family: "Fontisto", translate: "barco-a-vela" },
  { name: "snorkel", family: "Fontisto", translate: "máscara-de-mergulho" },
  { name: "suitcase-alt", family: "Fontisto", translate: "mala-alt" },
  { name: "suitcase", family: "Fontisto", translate: "mala" },
  { name: "sun", family: "Fontisto", translate: "sol" },
  {
    name: "sunglasses-alt",
    family: "Fontisto",
    translate: "óculos-de-sol-alt",
  },
  { name: "swimsuit", family: "Fontisto", translate: "traje-de-banho" },
  { name: "tent", family: "Fontisto", translate: "barraca" },
  { name: "ticket-alt", family: "Fontisto", translate: "bilhete-alt" },
  { name: "train-ticket", family: "Fontisto", translate: "bilhete-de-trem" },
  { name: "wallet", family: "Fontisto", translate: "carteira" },
  { name: "circle-o-notch", family: "Fontisto", translate: "círculo-o-notch" },
  { name: "propeller-1", family: "Fontisto", translate: "hélice-1" },
  { name: "propeller-2", family: "Fontisto", translate: "hélice-2" },
  { name: "propeller-3", family: "Fontisto", translate: "hélice-3" },
  { name: "propeller-4", family: "Fontisto", translate: "hélice-4" },
  { name: "spinner-cog", family: "Fontisto", translate: "girador-engrenagem" },
  { name: "spinner-fidget", family: "Fontisto", translate: "girador-fidget" },
  {
    name: "spinner-refresh",
    family: "Fontisto",
    translate: "girador-atualizar",
  },
  {
    name: "spinner-rotate-forward",
    family: "Fontisto",
    translate: "girador-rotacionar-avançar",
  },
  { name: "spinner", family: "Fontisto", translate: "girador" },
  { name: "snowflake", family: "Fontisto", translate: "floco-de-neve" },
  { name: "snowflake-1", family: "Fontisto", translate: "floco-de-neve-1" },
  { name: "snowflake-2", family: "Fontisto", translate: "floco-de-neve-2" },
  { name: "snowflake-3", family: "Fontisto", translate: "floco-de-neve-3" },
  { name: "snowflake-4", family: "Fontisto", translate: "floco-de-neve-4" },
  { name: "snowflake-5", family: "Fontisto", translate: "floco-de-neve-5" },
  { name: "snowflake-6", family: "Fontisto", translate: "floco-de-neve-6" },
  { name: "snowflake-7", family: "Fontisto", translate: "floco-de-neve-7" },
  { name: "snowflake-8", family: "Fontisto", translate: "floco-de-neve-8" },
  { name: "curve", family: "Fontisto", translate: "curva" },
  { name: "ellipse", family: "Fontisto", translate: "elipse" },
  { name: "rectangle", family: "Fontisto", translate: "retângulo" },
  { name: "shield", family: "Fontisto", translate: "escudo" },
  {
    name: "address-book",
    family: "Foundation",
    translate: "livro de endereços",
  },
  { name: "alert", family: "Foundation", translate: "alerta" },
  {
    name: "align-center",
    family: "Foundation",
    translate: "alinhar ao centro",
  },
  {
    name: "align-justify",
    family: "Foundation",
    translate: "alinhar justificado",
  },
  { name: "align-left", family: "Foundation", translate: "alinhar à esquerda" },
  { name: "align-right", family: "Foundation", translate: "alinhar à direita" },
  { name: "anchor", family: "Foundation", translate: "âncora" },
  { name: "annotate", family: "Foundation", translate: "anotar" },
  { name: "archive", family: "Foundation", translate: "arquivo" },
  { name: "arrow-down", family: "Foundation", translate: "seta para baixo" },
  { name: "social-pinterest", family: "Foundation", translate: "pinterest" },
  { name: "social-rdio", family: "Foundation", translate: "rdio" },
  { name: "social-reddit", family: "Foundation", translate: "reddit" },
  { name: "social-skillshare", family: "Foundation", translate: "skillshare" },
  { name: "social-skype", family: "Foundation", translate: "skype" },
  {
    name: "social-smashing-mag",
    family: "Foundation",
    translate: "smashing magazine",
  },
  { name: "social-snapchat", family: "Foundation", translate: "snapchat" },
  { name: "social-spotify", family: "Foundation", translate: "spotify" },
  { name: "social-squidoo", family: "Foundation", translate: "squidoo" },
  {
    name: "social-stack-overflow",
    family: "Foundation",
    translate: "stack overflow",
  },
  { name: "social-steam", family: "Foundation", translate: "steam" },
  {
    name: "social-stumbleupon",
    family: "Foundation",
    translate: "stumbleupon",
  },
  { name: "social-treehouse", family: "Foundation", translate: "treehouse" },
  { name: "social-tumblr", family: "Foundation", translate: "tumblr" },
  { name: "social-twitter", family: "Foundation", translate: "twitter" },
  { name: "social-vimeo", family: "Foundation", translate: "vimeo" },
  { name: "social-windows", family: "Foundation", translate: "windows" },
  { name: "social-xbox", family: "Foundation", translate: "xbox" },
  { name: "social-yahoo", family: "Foundation", translate: "yahoo" },
  { name: "social-yelp", family: "Foundation", translate: "yelp" },
  { name: "social-youtube", family: "Foundation", translate: "youtube" },
  { name: "social-zerply", family: "Foundation", translate: "zerply" },
  { name: "social-zurb", family: "Foundation", translate: "zurb" },
  { name: "sound", family: "Foundation", translate: "som" },
  { name: "star", family: "Foundation", translate: "estrela" },
  { name: "stop", family: "Foundation", translate: "parar" },
  { name: "strikethrough", family: "Foundation", translate: "tachado" },
  { name: "subscript", family: "Foundation", translate: "subscrito" },
  { name: "superscript", family: "Foundation", translate: "sobrescrito" },
  {
    name: "tablet-landscape",
    family: "Foundation",
    translate: "tablet paisagem",
  },
  {
    name: "tablet-portrait",
    family: "Foundation",
    translate: "tablet retrato",
  },
  { name: "target-two", family: "Foundation", translate: "alvo dois" },
  { name: "target", family: "Foundation", translate: "alvo" },
  {
    name: "telephone-accessible",
    family: "Foundation",
    translate: "telefone acessível",
  },
  { name: "telephone", family: "Foundation", translate: "telefone" },
  { name: "text-color", family: "Foundation", translate: "cor do texto" },
  { name: "thumbnails", family: "Foundation", translate: "miniaturas" },
  { name: "ticket", family: "Foundation", translate: "bilhete" },
  {
    name: "torso-business",
    family: "Foundation",
    translate: "torso de negócios",
  },
  { name: "torso-female", family: "Foundation", translate: "torso feminino" },
  { name: "torso", family: "Foundation", translate: "torso" },
  {
    name: "torsos-all-female",
    family: "Foundation",
    translate: "torsos todos femininos",
  },
  { name: "torsos-all", family: "Foundation", translate: "torsos todos" },
  {
    name: "torsos-female-male",
    family: "Foundation",
    translate: "torsos feminino masculino",
  },
  {
    name: "torsos-male-female",
    family: "Foundation",
    translate: "torsos masculino feminino",
  },
  { name: "torsos", family: "Foundation", translate: "torsos" },
  { name: "trash", family: "Foundation", translate: "lixeira" },
  { name: "trees", family: "Foundation", translate: "árvores" },
  { name: "trophy", family: "Foundation", translate: "troféu" },
  { name: "underline", family: "Foundation", translate: "sublinhado" },
  {
    name: "universal-access",
    family: "Foundation",
    translate: "acesso universal",
  },
  { name: "unlink", family: "Foundation", translate: "desvincular" },
  { name: "unlock", family: "Foundation", translate: "desbloquear" },
  {
    name: "upload-cloud",
    family: "Foundation",
    translate: "carregar na nuvem",
  },
  { name: "upload", family: "Foundation", translate: "carregar" },
  { name: "usb", family: "Foundation", translate: "usb" },
  { name: "video", family: "Foundation", translate: "vídeo" },
  { name: "volume-none", family: "Foundation", translate: "volume nenhum" },
  {
    name: "volume-strike",
    family: "Foundation",
    translate: "volume silenciado",
  },
  { name: "volume", family: "Foundation", translate: "volume" },
  { name: "web", family: "Foundation", translate: "web" },
  { name: "wheelchair", family: "Foundation", translate: "cadeira de rodas" },
  { name: "widget", family: "Foundation", translate: "widget" },
  { name: "wrench", family: "Foundation", translate: "chave inglesa" },
  { name: "x-circle", family: "Foundation", translate: "círculo x" },
  { name: "x", family: "Foundation", translate: "x" },
  { name: "yen", family: "Foundation", translate: "iene" },
  { name: "zoom-in", family: "Foundation", translate: "zoom in" },
  { name: "zoom-out", family: "Foundation", translate: "zoom out" },
  { name: "trash-bin-sharp", family: "Ionicons", translate: "lixeira" },
  { name: "trash-outline", family: "Ionicons", translate: "lixeira" },
  { name: "trash-sharp", family: "Ionicons", translate: "lixeira" },
  {
    name: "trending-down",
    family: "Ionicons",
    translate: "tendência-para-baixo",
  },
  {
    name: "trending-down-outline",
    family: "Ionicons",
    translate: "tendência-para-baixo",
  },
  {
    name: "trending-down-sharp",
    family: "Ionicons",
    translate: "tendência-para-baixo",
  },
  { name: "trending-up", family: "Ionicons", translate: "tendência-para-cima" },
  {
    name: "trending-up-outline",
    family: "Ionicons",
    translate: "tendência-para-cima",
  },
  {
    name: "trending-up-sharp",
    family: "Ionicons",
    translate: "tendência-para-cima",
  },
  { name: "triangle", family: "Ionicons", translate: "triângulo" },
  {
    name: "triangle-outline",
    family: "Ionicons",
    translate: "triângulo",
  },
  { name: "triangle-sharp", family: "Ionicons", translate: "triângulo" },
  { name: "trophy", family: "Ionicons", translate: "troféu" },
  { name: "trophy-outline", family: "Ionicons", translate: "troféu" },
  { name: "trophy-sharp", family: "Ionicons", translate: "troféu" },
  { name: "tv", family: "Ionicons", translate: "televisão" },
  { name: "tv-outline", family: "Ionicons", translate: "televisão" },
  { name: "tv-sharp", family: "Ionicons", translate: "televisão" },
  { name: "umbrella", family: "Ionicons", translate: "guarda-chuva" },
  {
    name: "umbrella-outline",
    family: "Ionicons",
    translate: "guarda-chuva",
  },
  {
    name: "umbrella-sharp",
    family: "Ionicons",
    translate: "guarda-chuva",
  },
  { name: "unlink", family: "Ionicons", translate: "desvincular" },
  {
    name: "unlink-outline",
    family: "Ionicons",
    translate: "desvincular",
  },
  { name: "unlink-sharp", family: "Ionicons", translate: "desvincular" },
  { name: "videocam", family: "Ionicons", translate: "câmera-de-vídeo" },
  {
    name: "videocam-off",
    family: "Ionicons",
    translate: "câmera-de-vídeo-desligada",
  },
  {
    name: "videocam-off-outline",
    family: "Ionicons",
    translate: "câmera-de-vídeo-desligada",
  },
  {
    name: "videocam-off-sharp",
    family: "Ionicons",
    translate: "câmera-de-vídeo-desligada",
  },
  {
    name: "videocam-outline",
    family: "Ionicons",
    translate: "câmera-de-vídeo",
  },
  {
    name: "videocam-sharp",
    family: "Ionicons",
    translate: "câmera-de-vídeo",
  },
  { name: "volume-high", family: "Ionicons", translate: "volume-alto" },
  {
    name: "volume-high-outline",
    family: "Ionicons",
    translate: "volume-alto",
  },
  {
    name: "volume-high-sharp",
    family: "Ionicons",
    translate: "volume-alto",
  },
  { name: "volume-low", family: "Ionicons", translate: "volume-baixo" },
  {
    name: "volume-low-outline",
    family: "Ionicons",
    translate: "volume-baixo",
  },
  {
    name: "volume-low-sharp",
    family: "Ionicons",
    translate: "volume-baixo",
  },
  { name: "volume-medium", family: "Ionicons", translate: "volume-médio" },
  {
    name: "volume-medium-outline",
    family: "Ionicons",
    translate: "volume-médio",
  },
  {
    name: "volume-medium-sharp",
    family: "Ionicons",
    translate: "volume-médio",
  },
  { name: "volume-mute", family: "Ionicons", translate: "volume-mudo" },
  {
    name: "volume-mute-outline",
    family: "Ionicons",
    translate: "volume-mudo",
  },
  {
    name: "volume-mute-sharp",
    family: "Ionicons",
    translate: "volume-mudo",
  },
  { name: "volume-off", family: "Ionicons", translate: "volume-desligado" },
  {
    name: "volume-off-outline",
    family: "Ionicons",
    translate: "volume-desligado",
  },
  {
    name: "volume-off-sharp",
    family: "Ionicons",
    translate: "volume-desligado",
  },
  { name: "walk", family: "Ionicons", translate: "andar" },
  { name: "walk-outline", family: "Ionicons", translate: "andar" },
  { name: "walk-sharp", family: "Ionicons", translate: "andar" },
  { name: "wallet", family: "Ionicons", translate: "carteira" },
  {
    name: "wallet-outline",
    family: "Ionicons",
    translate: "carteira",
  },
  { name: "wallet-sharp", family: "Ionicons", translate: "carteira" },
  { name: "warning", family: "Ionicons", translate: "alerta" },
  { name: "warning-outline", family: "Ionicons", translate: "alerta" },
  { name: "warning-sharp", family: "Ionicons", translate: "alerta" },
  { name: "watch", family: "Ionicons", translate: "relógio" },
  { name: "watch-outline", family: "Ionicons", translate: "relógio" },
  { name: "watch-sharp", family: "Ionicons", translate: "relógio" },
  { name: "water", family: "Ionicons", translate: "água" },
  { name: "water-outline", family: "Ionicons", translate: "água" },
  { name: "water-sharp", family: "Ionicons", translate: "água" },
  { name: "wifi", family: "Ionicons", translate: "wifi" },
  { name: "wifi-outline", family: "Ionicons", translate: "wifi" },
  { name: "wifi-sharp", family: "Ionicons", translate: "wifi" },
  { name: "wine", family: "Ionicons", translate: "vinho" },
  { name: "wine-outline", family: "Ionicons", translate: "vinho" },
  { name: "wine-sharp", family: "Ionicons", translate: "vinho" },
  { name: "woman", family: "Ionicons", translate: "mulher" },
  { name: "woman-outline", family: "Ionicons", translate: "mulher" },
  { name: "woman-sharp", family: "Ionicons", translate: "mulher" },
  {
    name: "wifi-strength-4",
    family: "MaterialCommunityIcons",
    translate: "força-de-wifi-4",
  },
  {
    name: "wifi-strength-4-alert",
    family: "MaterialCommunityIcons",
    translate: "alerta-de-força-de-wifi-4",
  },
  {
    name: "wifi-strength-4-lock",
    family: "MaterialCommunityIcons",
    translate: "força-de-wifi-4-trava",
  },
  {
    name: "wifi-strength-4-lock-open",
    family: "MaterialCommunityIcons",
    translate: "força-de-wifi-4-trava-aberta",
  },
  {
    name: "wifi-strength-alert-outline",
    family: "MaterialCommunityIcons",
    translate: "contorno-de-alerta-de-força-de-wifi",
  },
  {
    name: "wifi-strength-lock-open-outline",
    family: "MaterialCommunityIcons",
    translate: "contorno-de-trava-aberta-de-força-de-wifi",
  },
  {
    name: "wifi-strength-lock-outline",
    family: "MaterialCommunityIcons",
    translate: "contorno-de-trava-de-força-de-wifi",
  },
  {
    name: "wifi-strength-off",
    family: "MaterialCommunityIcons",
    translate: "wifi-fora",
  },
  {
    name: "wifi-strength-off-outline",
    family: "MaterialCommunityIcons",
    translate: "contorno-de-wifi-fora",
  },
  {
    name: "wifi-strength-outline",
    family: "MaterialCommunityIcons",
    translate: "contorno-de-força-de-wifi",
  },
  {
    name: "wifi-sync",
    family: "MaterialCommunityIcons",
    translate: "sincronização-de-wifi",
  },
  {
    name: "wikipedia",
    family: "MaterialCommunityIcons",
    translate: "wikipedia",
  },
  {
    name: "wind-turbine",
    family: "MaterialCommunityIcons",
    translate: "turbina-eolica",
  },
  {
    name: "wind-turbine-alert",
    family: "MaterialCommunityIcons",
    translate: "alerta-de-turbina-eolica",
  },
  {
    name: "wind-turbine-check",
    family: "MaterialCommunityIcons",
    translate: "verificacao-de-turbina-eolica",
  },
  {
    name: "window-close",
    family: "MaterialCommunityIcons",
    translate: "janela-fechada",
  },
  {
    name: "window-closed",
    family: "MaterialCommunityIcons",
    translate: "janela-fechada",
  },
  {
    name: "window-closed-variant",
    family: "MaterialCommunityIcons",
    translate: "variante-de-janela-fechada",
  },
  {
    name: "window-maximize",
    family: "MaterialCommunityIcons",
    translate: "maximizar-janela",
  },
  {
    name: "window-minimize",
    family: "MaterialCommunityIcons",
    translate: "minimizar-janela",
  },
  {
    name: "window-open",
    family: "MaterialCommunityIcons",
    translate: "janela-aberta",
  },
  {
    name: "window-open-variant",
    family: "MaterialCommunityIcons",
    translate: "variante-de-janela-aberta",
  },
  {
    name: "window-restore",
    family: "MaterialCommunityIcons",
    translate: "restaurar-janela",
  },
  {
    name: "window-shutter",
    family: "MaterialCommunityIcons",
    translate: "persiana-de-janela",
  },
  {
    name: "window-shutter-alert",
    family: "MaterialCommunityIcons",
    translate: "alerta-de-persiana-de-janela",
  },
  {
    name: "window-shutter-open",
    family: "MaterialCommunityIcons",
    translate: "persiana-de-janela-aberta",
  },
  {
    name: "windsock",
    family: "MaterialCommunityIcons",
    translate: "sinal-de-vento",
  },
  {
    name: "wiper",
    family: "MaterialCommunityIcons",
    translate: "limpador-de-parabrisas",
  },
  {
    name: "wiper-wash",
    family: "MaterialCommunityIcons",
    translate: "lavagem-de-limpador-de-parabrisas",
  },
  {
    name: "wiper-wash-alert",
    family: "MaterialCommunityIcons",
    translate: "alerta-de-lavagem-de-limpador-de-parabrisas",
  },
  {
    name: "wizard-hat",
    family: "MaterialCommunityIcons",
    translate: "chapéu-de-feiticeiro",
  },
  {
    name: "wordpress",
    family: "MaterialCommunityIcons",
    translate: "wordpress",
  },
  { name: "wrap", family: "MaterialCommunityIcons", translate: "embrulho" },
  {
    name: "wrap-disabled",
    family: "MaterialCommunityIcons",
    translate: "embrulho-desabilitado",
  },
  { name: "wrench", family: "MaterialCommunityIcons", translate: "chave" },
  {
    name: "wrench-clock",
    family: "MaterialCommunityIcons",
    translate: "chave-relógio",
  },
  {
    name: "wrench-outline",
    family: "MaterialCommunityIcons",
    translate: "contorno-de-chave",
  },
  { name: "xamarin", family: "MaterialCommunityIcons", translate: "xamarin" },
  { name: "xml", family: "MaterialCommunityIcons", translate: "xml" },
  { name: "xmpp", family: "MaterialCommunityIcons", translate: "xmpp" },
  { name: "yahoo", family: "MaterialCommunityIcons", translate: "yahoo" },
  { name: "yeast", family: "MaterialCommunityIcons", translate: "fermento" },
  { name: "yin-yang", family: "MaterialCommunityIcons", translate: "yin-yang" },
  { name: "yoga", family: "MaterialCommunityIcons", translate: "yoga" },
  { name: "youtube", family: "MaterialCommunityIcons", translate: "youtube" },
  {
    name: "youtube-gaming",
    family: "MaterialCommunityIcons",
    translate: "youtube-jogos",
  },
  {
    name: "youtube-studio",
    family: "MaterialCommunityIcons",
    translate: "estudio-do-youtube",
  },
  {
    name: "youtube-subscription",
    family: "MaterialCommunityIcons",
    translate: "assinatura-do-youtube",
  },
  {
    name: "youtube-tv",
    family: "MaterialCommunityIcons",
    translate: "tv-do-youtube",
  },
  { name: "yurt", family: "MaterialCommunityIcons" },
  { name: "z-wave", family: "MaterialCommunityIcons", translate: "z-wave" },
  { name: "zend", family: "MaterialCommunityIcons", translate: "zend" },
  { name: "zigbee", family: "MaterialCommunityIcons", translate: "zigbee" },
  { name: "zip-box", family: "MaterialCommunityIcons", translate: "caixa-zip" },
  {
    name: "zip-box-outline",
    family: "MaterialCommunityIcons",
    translate: "contorno-de-caixa-zip",
  },
  {
    name: "zip-disk",
    family: "MaterialCommunityIcons",
    translate: "disco-zip",
  },
  {
    name: "zodiac-aquarius",
    family: "MaterialCommunityIcons",
    translate: "zodiaco-aquario",
  },
  {
    name: "zodiac-aries",
    family: "MaterialCommunityIcons",
    translate: "zodiaco-aries",
  },
  {
    name: "zodiac-cancer",
    family: "MaterialCommunityIcons",
    translate: "zodiaco-cancer",
  },
  {
    name: "zodiac-capricorn",
    family: "MaterialCommunityIcons",
    translate: "zodiaco-capricornio",
  },
  {
    name: "zodiac-gemini",
    family: "MaterialCommunityIcons",
    translate: "zodiaco-gemeos",
  },
  {
    name: "zodiac-leo",
    family: "MaterialCommunityIcons",
    translate: "zodiaco-leao",
  },
  {
    name: "zodiac-libra",
    family: "MaterialCommunityIcons",
    translate: "zodiaco-libra",
  },
  {
    name: "zodiac-pisces",
    family: "MaterialCommunityIcons",
    translate: "zodiaco-peixes",
  },
  {
    name: "zodiac-sagittarius",
    family: "MaterialCommunityIcons",
    translate: "zodiaco-sagitario",
  },
  {
    name: "zodiac-scorpio",
    family: "MaterialCommunityIcons",
    translate: "zodiaco-escorpiao",
  },
  {
    name: "zodiac-taurus",
    family: "MaterialCommunityIcons",
    translate: "zodiaco-touro",
  },
  {
    name: "zodiac-virgo",
    family: "MaterialCommunityIcons",
    translate: "zodiaco-virgem",
  },
  { name: "blank", family: "MaterialCommunityIcons", translate: "em-branco" },
  { name: "123", family: "MaterialIcons", translate: "123" },
  { name: "360", family: "MaterialIcons", translate: "360" },
  { name: "10k", family: "MaterialIcons", translate: "10k" },
  { name: "10mp", family: "MaterialIcons", translate: "10 megapixels" },
  { name: "11mp", family: "MaterialIcons", translate: "11 megapixels" },
  { name: "12mp", family: "MaterialIcons", translate: "12 megapixels" },
  { name: "13mp", family: "MaterialIcons", translate: "13 megapixels" },
  { name: "14mp", family: "MaterialIcons", translate: "14 megapixels" },
  { name: "15mp", family: "MaterialIcons", translate: "15 megapixels" },
  { name: "16mp", family: "MaterialIcons", translate: "16 megapixels" },
  { name: "water", family: "MaterialIcons", translate: "água" },
  { name: "water-damage", family: "MaterialIcons", translate: "dano na água" },
  { name: "water-drop", family: "MaterialIcons", translate: "gota de água" },
  {
    name: "waterfall-chart",
    family: "MaterialIcons",
    translate: "gráfico de cascata",
  },
  { name: "waves", family: "MaterialIcons", translate: "ondas" },
  { name: "waving-hand", family: "MaterialIcons", translate: "mão acenando" },
  {
    name: "wb-auto",
    family: "MaterialIcons",
    translate: "equilíbrio de branco automático",
  },
  {
    name: "wb-cloudy",
    family: "MaterialIcons",
    translate: "equilíbrio de branco nublado",
  },
  {
    name: "wb-incandescent",
    family: "MaterialIcons",
    translate: "equilíbrio de branco incandescente",
  },
  {
    name: "wb-iridescent",
    family: "MaterialIcons",
    translate: "equilíbrio de branco iridescente",
  },
  {
    name: "wb-shade",
    family: "MaterialIcons",
    translate: "equilíbrio de branco sombra",
  },
  {
    name: "wb-sunny",
    family: "MaterialIcons",
    translate: "equilíbrio de branco ensolarado",
  },
  {
    name: "wb-twighlight",
    family: "MaterialIcons",
    translate: "equilíbrio de branco entardecer",
  },
  {
    name: "wb-twilight",
    family: "MaterialIcons",
    translate: "equilíbrio de branco amanhecer",
  },
  { name: "wc", family: "MaterialIcons", translate: "banheiro" },
  { name: "web", family: "MaterialIcons", translate: "web" },
  { name: "web-asset", family: "MaterialIcons", translate: "recurso da web" },
  {
    name: "web-asset-off",
    family: "MaterialIcons",
    translate: "recurso da web desativado",
  },
  {
    name: "web-stories",
    family: "MaterialIcons",
    translate: "histórias da web",
  },
  { name: "webhook", family: "MaterialIcons", translate: "webhook" },
  { name: "wechat", family: "MaterialIcons", translate: "wechat" },
  { name: "weekend", family: "MaterialIcons", translate: "fim de semana" },
  { name: "west", family: "MaterialIcons", translate: "oeste" },
  { name: "whatshot", family: "MaterialIcons", translate: "o que está quente" },
  {
    name: "wheelchair-pickup",
    family: "MaterialIcons",
    translate: "cadeira de rodas pega",
  },
  { name: "where-to-vote", family: "MaterialIcons", translate: "onde votar" },
  { name: "widgets", family: "MaterialIcons", translate: "widgets" },
  { name: "width-full", family: "MaterialIcons", translate: "largura total" },
  {
    name: "width-normal",
    family: "MaterialIcons",
    translate: "largura normal",
  },
  { name: "width-wide", family: "MaterialIcons", translate: "largura ampla" },
  { name: "wifi", family: "MaterialIcons", translate: "wifi" },
  { name: "wifi-1-bar", family: "MaterialIcons", translate: "wifi 1 barra" },
  { name: "wifi-2-bar", family: "MaterialIcons", translate: "wifi 2 barras" },
  { name: "wifi-calling", family: "MaterialIcons", translate: "chamada wifi" },
  {
    name: "wifi-calling-3",
    family: "MaterialIcons",
    translate: "chamada wifi 3",
  },
  { name: "wifi-channel", family: "MaterialIcons", translate: "canal wifi" },
  { name: "wifi-find", family: "MaterialIcons", translate: "encontrar wifi" },
  { name: "wifi-lock", family: "MaterialIcons", translate: "wifi bloqueado" },
  { name: "wifi-off", family: "MaterialIcons", translate: "wifi desativado" },
  { name: "wifi-password", family: "MaterialIcons", translate: "senha wifi" },
  {
    name: "wifi-protected-setup",
    family: "MaterialIcons",
    translate: "configuração wifi protegida",
  },
  {
    name: "wifi-tethering",
    family: "MaterialIcons",
    translate: "compartilhamento de wifi",
  },
  {
    name: "wifi-tethering-error",
    family: "MaterialIcons",
    translate: "erro no compartilhamento de wifi",
  },
  {
    name: "wifi-tethering-error-rounded",
    family: "MaterialIcons",
    translate: "erro no compartilhamento de wifi arredondado",
  },
  {
    name: "wifi-tethering-off",
    family: "MaterialIcons",
    translate: "compartilhamento de wifi desativado",
  },
  { name: "wind-power", family: "MaterialIcons", translate: "energia eólica" },
  { name: "window", family: "MaterialIcons", translate: "janela" },
  { name: "wine-bar", family: "MaterialIcons", translate: "bar de vinhos" },
  { name: "woman", family: "MaterialIcons", translate: "mulher" },
  { name: "woman-2", family: "MaterialIcons", translate: "mulher 2" },
  { name: "woo-commerce", family: "MaterialIcons", translate: "woo-commerce" },
  { name: "wordpress", family: "MaterialIcons", translate: "wordpress" },
  { name: "work", family: "MaterialIcons", translate: "trabalho" },
  {
    name: "work-history",
    family: "MaterialIcons",
    translate: "histórico de trabalho",
  },
  {
    name: "work-off",
    family: "MaterialIcons",
    translate: "trabalho desativado",
  },
  {
    name: "work-outline",
    family: "MaterialIcons",
    translate: "trabalho",
  },
  {
    name: "workspace-premium",
    family: "MaterialIcons",
    translate: "espaço de trabalho premium",
  },
  {
    name: "workspaces",
    family: "MaterialIcons",
    translate: "espaços de trabalho",
  },
  {
    name: "workspaces-filled",
    family: "MaterialIcons",
    translate: "espaços de trabalho preenchidos",
  },
  {
    name: "workspaces-outline",
    family: "MaterialIcons",
    translate: " espaços de trabalho",
  },
  { name: "wrap-text", family: "MaterialIcons", translate: "quebrar texto" },
  {
    name: "wrong-location",
    family: "MaterialIcons",
    translate: "localização errada",
  },
  { name: "wysiwyg", family: "MaterialIcons", translate: "WYSIWYG" },
  { name: "yard", family: "MaterialIcons", translate: "quintal" },
  {
    name: "youtube-searched-for",
    family: "MaterialIcons",
    translate: "youtube pesquisado",
  },
  { name: "zoom-in", family: "MaterialIcons", translate: "zoom in" },
  {
    name: "zoom-in-map",
    family: "MaterialIcons",
    translate: "zoom in no mapa",
  },
  { name: "zoom-out", family: "MaterialIcons", translate: "zoom out" },
  {
    name: "zoom-out-map",
    family: "MaterialIcons",
    translate: "zoom out no mapa",
  },
  { name: "accessibility", family: "Octicons", translate: "acessibilidade" },
  { name: "alert", family: "Octicons", translate: "alerta" },
  { name: "apps", family: "Octicons", translate: "aplicativos" },
  { name: "archive", family: "Octicons", translate: "arquivo" },
  { name: "arrow-both", family: "Octicons", translate: "seta-dupla" },
  { name: "arrow-down", family: "Octicons", translate: "seta-baixo" },
  { name: "arrow-left", family: "Octicons", translate: "seta-esquerda" },
  { name: "arrow-right", family: "Octicons", translate: "seta-direita" },
  { name: "arrow-switch", family: "Octicons", translate: "trocar-seta" },
  { name: "arrow-up", family: "Octicons", translate: "seta-cima" },
  { name: "repo-pull", family: "Octicons", translate: "repositório-puxar" },
  { name: "repo-push", family: "Octicons", translate: "repositório-enviar" },
  {
    name: "repo-template",
    family: "Octicons",
    translate: "repositório-modelo",
  },
  { name: "report", family: "Octicons", translate: "relatório" },
  { name: "rocket", family: "Octicons", translate: "foguete" },
  { name: "rows", family: "Octicons", translate: "linhas" },
  { name: "rss", family: "Octicons", translate: "rss" },
  { name: "ruby", family: "Octicons", translate: "ruby" },
  { name: "screen-full", family: "Octicons", translate: "tela-cheia" },
  { name: "screen-normal", family: "Octicons", translate: "tela-normal" },
  { name: "search", family: "Octicons", translate: "pesquisar" },
  { name: "server", family: "Octicons", translate: "servidor" },
  { name: "share", family: "Octicons", translate: "compartilhar" },
  {
    name: "share-android",
    family: "Octicons",
    translate: "compartilhar-android",
  },
  { name: "shield", family: "Octicons", translate: "escudo" },
  { name: "shield-check", family: "Octicons", translate: "escudo-verificar" },
  { name: "shield-lock", family: "Octicons", translate: "escudo-bloquear" },
  { name: "shield-x", family: "Octicons", translate: "escudo-x" },
  {
    name: "sidebar-collapse",
    family: "Octicons",
    translate: "barra-lateral-recolher",
  },
  {
    name: "sidebar-expand",
    family: "Octicons",
    translate: "barra-lateral-expandir",
  },
  { name: "sign-in", family: "Octicons", translate: "entrar" },
  { name: "sign-out", family: "Octicons", translate: "sair" },
  { name: "single-select", family: "Octicons", translate: "seleção-única" },
  { name: "skip", family: "Octicons", translate: "pular" },
  { name: "smiley", family: "Octicons", translate: "carinha" },
  { name: "sort-asc", family: "Octicons", translate: "ordenar-ascendente" },
  { name: "sort-desc", family: "Octicons", translate: "ordenar-descendente" },
  { name: "square", family: "Octicons", translate: "quadrado" },
  { name: "square-fill", family: "Octicons", translate: "quadrado-preenchido" },
  { name: "squirrel", family: "Octicons", translate: "esquilo" },
  { name: "stack", family: "Octicons", translate: "pilha" },
  { name: "star", family: "Octicons", translate: "estrela" },
  { name: "star-fill", family: "Octicons", translate: "estrela-preenchida" },
  { name: "stop", family: "Octicons", translate: "parar" },
  { name: "stopwatch", family: "Octicons", translate: "cronômetro" },
  { name: "strikethrough", family: "Octicons", translate: "riscado" },
  { name: "sun", family: "Octicons", translate: "sol" },
  { name: "sync", family: "Octicons", translate: "sincronizar" },
  { name: "tab-external", family: "Octicons", translate: "aba-externa" },
  { name: "table", family: "Octicons", translate: "tabela" },
  { name: "tag", family: "Octicons", translate: "etiqueta" },
  { name: "tasklist", family: "Octicons", translate: "lista-tarefas" },
  { name: "telescope", family: "Octicons", translate: "telescópio" },
  {
    name: "telescope-fill",
    family: "Octicons",
    translate: "telescópio-preenchido",
  },
  { name: "terminal", family: "Octicons", translate: "terminal" },
  { name: "three-bars", family: "Octicons", translate: "três-barras" },
  { name: "thumbsdown", family: "Octicons", translate: "dedo-para-baixo" },
  { name: "thumbsup", family: "Octicons", translate: "dedo-para-cima" },
  { name: "tools", family: "Octicons", translate: "ferramentas" },
  { name: "trash", family: "Octicons", translate: "lixo" },
  {
    name: "triangle-down",
    family: "Octicons",
    translate: "triângulo-para-baixo",
  },
  {
    name: "triangle-left",
    family: "Octicons",
    translate: "triângulo-para-esquerda",
  },
  {
    name: "triangle-right",
    family: "Octicons",
    translate: "triângulo-para-direita",
  },
  { name: "triangle-up", family: "Octicons", translate: "triângulo-para-cima" },
  { name: "typography", family: "Octicons", translate: "tipografia" },
  { name: "unfold", family: "Octicons", translate: "desdobrar" },
  { name: "unlock", family: "Octicons", translate: "desbloquear" },
  { name: "unmute", family: "Octicons", translate: "desmudo" },
  { name: "unverified", family: "Octicons", translate: "não-verificado" },
  { name: "upload", family: "Octicons", translate: "enviar" },
  { name: "verified", family: "Octicons", translate: "verificado" },
  { name: "versions", family: "Octicons", translate: "versões" },
  { name: "video", family: "Octicons", translate: "vídeo" },
  { name: "webhook", family: "Octicons", translate: "webhook" },
  { name: "workflow", family: "Octicons", translate: "fluxo-trabalho" },
  { name: "x", family: "Octicons", translate: "x" },
  { name: "x-circle", family: "Octicons", translate: "círculo-x" },
  {
    name: "x-circle-fill",
    family: "Octicons",
    translate: "círculo-x-preenchido",
  },
  { name: "zap", family: "Octicons", translate: "raio" },
  { name: "user", family: "SimpleLineIcons", translate: "usuário" },
  { name: "people", family: "SimpleLineIcons", translate: "pessoas" },
  {
    name: "user-female",
    family: "SimpleLineIcons",
    translate: "usuário-feminino",
  },
  {
    name: "user-follow",
    family: "SimpleLineIcons",
    translate: "seguir-usuário",
  },
  {
    name: "user-following",
    family: "SimpleLineIcons",
    translate: "seguindo-usuário",
  },
  {
    name: "user-unfollow",
    family: "SimpleLineIcons",
    translate: "deixar-de-seguir",
  },
  { name: "login", family: "SimpleLineIcons", translate: "entrar" },
  { name: "logout", family: "SimpleLineIcons", translate: "sair" },
  { name: "emotsmile", family: "SimpleLineIcons", translate: "carinha-feliz" },
  { name: "phone", family: "SimpleLineIcons", translate: "telefone" },
  {
    name: "music-tone-alt",
    family: "SimpleLineIcons",
    translate: "tom-musical-alt",
  },
  { name: "music-tone", family: "SimpleLineIcons", translate: "tom-musical" },
  { name: "earphones-alt", family: "SimpleLineIcons", translate: "fones-alt" },
  { name: "earphones", family: "SimpleLineIcons", translate: "fones" },
  { name: "equalizer", family: "SimpleLineIcons", translate: "equalizador" },
  { name: "like", family: "SimpleLineIcons", translate: "curtir" },
  { name: "dislike", family: "SimpleLineIcons", translate: "não-curtir" },
  {
    name: "control-start",
    family: "SimpleLineIcons",
    translate: "controle-iniciar",
  },
  {
    name: "control-rewind",
    family: "SimpleLineIcons",
    translate: "controle-voltar",
  },
  {
    name: "control-play",
    family: "SimpleLineIcons",
    translate: "controle-play",
  },
  {
    name: "control-pause",
    family: "SimpleLineIcons",
    translate: "controle-pausar",
  },
  {
    name: "control-forward",
    family: "SimpleLineIcons",
    translate: "controle-avançar",
  },
  { name: "control-end", family: "SimpleLineIcons", translate: "controle-fim" },
  { name: "volume-1", family: "SimpleLineIcons", translate: "volume-1" },
  { name: "volume-2", family: "SimpleLineIcons", translate: "volume-2" },
  {
    name: "volume-off",
    family: "SimpleLineIcons",
    translate: "volume-desligado",
  },
  { name: "calendar", family: "SimpleLineIcons", translate: "calendário" },
  { name: "bulb", family: "SimpleLineIcons", translate: "lâmpada" },
  { name: "chart", family: "SimpleLineIcons", translate: "gráfico" },
  { name: "ban", family: "SimpleLineIcons", translate: "banir" },
  { name: "bubble", family: "SimpleLineIcons", translate: "balão" },
  {
    name: "camrecorder",
    family: "SimpleLineIcons",
    translate: "gravador-câmera",
  },
  { name: "camera", family: "SimpleLineIcons", translate: "câmera" },
  {
    name: "cloud-download",
    family: "SimpleLineIcons",
    translate: "nuvem-baixar",
  },
  {
    name: "cloud-upload",
    family: "SimpleLineIcons",
    translate: "nuvem-enviar",
  },
  { name: "envelope", family: "SimpleLineIcons", translate: "envelope" },
  { name: "eye", family: "SimpleLineIcons", translate: "olho" },
  { name: "flag", family: "SimpleLineIcons", translate: "bandeira" },
  { name: "heart", family: "SimpleLineIcons", translate: "coração" },
  { name: "info", family: "SimpleLineIcons", translate: "informação" },
  { name: "key", family: "SimpleLineIcons", translate: "chave" },
  { name: "link", family: "SimpleLineIcons", translate: "link" },
  { name: "lock", family: "SimpleLineIcons", translate: "cadeado" },
  { name: "lock-open", family: "SimpleLineIcons", translate: "cadeado-aberto" },
  { name: "magnifier", family: "SimpleLineIcons", translate: "lupa" },
  {
    name: "magnifier-add",
    family: "SimpleLineIcons",
    translate: "lupa-adicionar",
  },
  {
    name: "magnifier-remove",
    family: "SimpleLineIcons",
    translate: "lupa-remover",
  },
  { name: "paper-clip", family: "SimpleLineIcons", translate: "clipe-papel" },
  { name: "paper-plane", family: "SimpleLineIcons", translate: "avião-papel" },
  { name: "power", family: "SimpleLineIcons", translate: "energia" },
  { name: "refresh", family: "SimpleLineIcons", translate: "atualizar" },
  { name: "reload", family: "SimpleLineIcons", translate: "recarregar" },
  { name: "settings", family: "SimpleLineIcons", translate: "configurações" },
  { name: "star", family: "SimpleLineIcons", translate: "estrela" },
  {
    name: "symbol-female",
    family: "SimpleLineIcons",
    translate: "símbolo-feminino",
  },
  {
    name: "symbol-male",
    family: "SimpleLineIcons",
    translate: "símbolo-masculino",
  },
  { name: "target", family: "SimpleLineIcons", translate: "alvo" },
  {
    name: "credit-card",
    family: "SimpleLineIcons",
    translate: "cartão-crédito",
  },
  { name: "paypal", family: "SimpleLineIcons", translate: "paypal" },
  {
    name: "social-tumblr",
    family: "SimpleLineIcons",
    translate: "social-tumblr",
  },
  {
    name: "social-twitter",
    family: "SimpleLineIcons",
    translate: "social-twitter",
  },
  {
    name: "social-facebook",
    family: "SimpleLineIcons",
    translate: "social-facebook",
  },
  {
    name: "social-instagram",
    family: "SimpleLineIcons",
    translate: "social-instagram",
  },
  {
    name: "social-linkedin",
    family: "SimpleLineIcons",
    translate: "social-linkedin",
  },
  {
    name: "social-pinterest",
    family: "SimpleLineIcons",
    translate: "social-pinterest",
  },
  {
    name: "social-github",
    family: "SimpleLineIcons",
    translate: "social-github",
  },
  {
    name: "social-google",
    family: "SimpleLineIcons",
    translate: "social-google",
  },
  {
    name: "social-reddit",
    family: "SimpleLineIcons",
    translate: "social-reddit",
  },
  {
    name: "social-skype",
    family: "SimpleLineIcons",
    translate: "social-skype",
  },
  {
    name: "social-dribbble",
    family: "SimpleLineIcons",
    translate: "social-dribbble",
  },
  {
    name: "social-behance",
    family: "SimpleLineIcons",
    translate: "social-behance",
  },
  {
    name: "social-foursqare",
    family: "SimpleLineIcons",
    translate: "social-foursquare",
  },
  {
    name: "social-soundcloud",
    family: "SimpleLineIcons",
    translate: "social-soundcloud",
  },
  {
    name: "social-spotify",
    family: "SimpleLineIcons",
    translate: "social-spotify",
  },
  {
    name: "social-stumbleupon",
    family: "SimpleLineIcons",
    translate: "social-stumbleupon",
  },
  {
    name: "social-youtube",
    family: "SimpleLineIcons",
    translate: "social-youtube",
  },
  {
    name: "social-dropbox",
    family: "SimpleLineIcons",
    translate: "social-dropbox",
  },
  {
    name: "social-vkontakte",
    family: "SimpleLineIcons",
    translate: "social-vkontakte",
  },
  {
    name: "social-steam",
    family: "SimpleLineIcons",
    translate: "social-steam",
  },
  { name: "acrobat", family: "Zocial", translate: "acrobat" },
  { name: "amazon", family: "Zocial", translate: "amazon" },
  { name: "android", family: "Zocial", translate: "android" },
  { name: "angellist", family: "Zocial", translate: "lista de anjos" },
  { name: "aol", family: "Zocial", translate: "aol" },
  { name: "appnet", family: "Zocial", translate: "rede de aplicativos" },
  { name: "appstore", family: "Zocial", translate: "loja de aplicativos" },
  { name: "bitbucket", family: "Zocial", translate: "bitbucket" },
  { name: "bitcoin", family: "Zocial", translate: "bitcoin" },
  { name: "blogger", family: "Zocial", translate: "blogueiro" },
  { name: "flattr", family: "Zocial", translate: "flattr" },
  { name: "flickr", family: "Zocial", translate: "flickr" },
  { name: "forrst", family: "Zocial", translate: "forrst" },
  { name: "foursquare", family: "Zocial", translate: "foursquare" },
  { name: "github", family: "Zocial", translate: "github" },
  { name: "gmail", family: "Zocial", translate: "gmail" },
  { name: "google", family: "Zocial", translate: "google" },
  { name: "googleplay", family: "Zocial", translate: "google play" },
  { name: "googleplus", family: "Zocial", translate: "google plus" },
  { name: "gowalla", family: "Zocial", translate: "gowalla" },
  { name: "grooveshark", family: "Zocial", translate: "grooveshark" },
  { name: "guest", family: "Zocial", translate: "convidado" },
  { name: "html5", family: "Zocial", translate: "html5" },
  { name: "ie", family: "Zocial", translate: "ie" },
  { name: "instagram", family: "Zocial", translate: "instagram" },
  { name: "instapaper", family: "Zocial", translate: "instapaper" },
  { name: "intensedebate", family: "Zocial", translate: "intensedebate" },
  { name: "itunes", family: "Zocial", translate: "itunes" },
  { name: "klout", family: "Zocial", translate: "klout" },
  { name: "lanyrd", family: "Zocial", translate: "lanyrd" },
  { name: "lastfm", family: "Zocial", translate: "lastfm" },
  { name: "lego", family: "Zocial", translate: "lego" },
  { name: "linkedin", family: "Zocial", translate: "linkedin" },
  { name: "lkdto", family: "Zocial", translate: "lkdto" },
  { name: "logmein", family: "Zocial", translate: "logmein" },
  { name: "macstore", family: "Zocial", translate: "macstore" },
  { name: "meetup", family: "Zocial", translate: "meetup" },
  { name: "myspace", family: "Zocial", translate: "myspace" },
  {
    name: "ninetyninedesigns",
    family: "Zocial",
    translate: "noventa e nove designs",
  },
  { name: "openid", family: "Zocial", translate: "openid" },
  { name: "opentable", family: "Zocial", translate: "opentable" },
  { name: "paypal", family: "Zocial", translate: "paypal" },
  { name: "persona", family: "Zocial", translate: "persona" },
  { name: "pinboard", family: "Zocial", translate: "pinboard" },
  { name: "pinterest", family: "Zocial", translate: "pinterest" },
  { name: "plancast", family: "Zocial", translate: "plancast" },
  { name: "plurk", family: "Zocial", translate: "plurk" },
  { name: "pocket", family: "Zocial", translate: "pocket" },
  { name: "podcast", family: "Zocial", translate: "podcast" },
  { name: "posterous", family: "Zocial", translate: "posterous" },
  { name: "print", family: "Zocial", translate: "imprimir" },
  { name: "quora", family: "Zocial", translate: "quora" },
  { name: "reddit", family: "Zocial", translate: "reddit" },
  { name: "rss", family: "Zocial", translate: "rss" },
  { name: "scribd", family: "Zocial", translate: "scribd" },
  { name: "skype", family: "Zocial", translate: "skype" },
  { name: "smashing", family: "Zocial", translate: "smashing" },
  { name: "songkick", family: "Zocial", translate: "songkick" },
  { name: "soundcloud", family: "Zocial", translate: "soundcloud" },
  { name: "spotify", family: "Zocial", translate: "spotify" },
  { name: "stackoverflow", family: "Zocial", translate: "stackoverflow" },
  { name: "statusnet", family: "Zocial", translate: "statusnet" },
  { name: "steam", family: "Zocial", translate: "steam" },
  { name: "stripe", family: "Zocial", translate: "stripe" },
  { name: "stumbleupon", family: "Zocial", translate: "stumbleupon" },
  { name: "tumblr", family: "Zocial", translate: "tumblr" },
  { name: "twitter", family: "Zocial", translate: "twitter" },
  { name: "viadeo", family: "Zocial", translate: "viadeo" },
  { name: "vimeo", family: "Zocial", translate: "vimeo" },
  { name: "vk", family: "Zocial", translate: "vk" },
  { name: "weibo", family: "Zocial", translate: "weibo" },
  { name: "wikipedia", family: "Zocial", translate: "wikipedia" },
  { name: "windows", family: "Zocial", translate: "windows" },
  { name: "wordpress", family: "Zocial", translate: "wordpress" },
  { name: "xing", family: "Zocial", translate: "xing" },
  { name: "yahoo", family: "Zocial", translate: "yahoo" },
  { name: "ycombinator", family: "Zocial", translate: "ycombinator" },
  { name: "yelp", family: "Zocial", translate: "yelp" },
  { name: "youtube", family: "Zocial", translate: "youtube" },
];
